// <auto-generated />
using LocalBusinessLookup.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessLookup.Migrations
{
    [DbContext(typeof(LocalBusinessLookupContext))]
    [Migration("20200612163009_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessLookup.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.Property<string>("WebSite");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 10,
                            Description = "A bold, bland take on the popular California burrito",
                            Name = "Jeff's Burritos",
                            PhoneNumber = "4355552221",
                            Type = "restaurant",
                            UserId = 1,
                            WebSite = "https://www.google.com/"
                        },
                        new
                        {
                            BusinessId = 11,
                            Description = "Castor oil rubbed into the scalp, every night before bed, for one week.",
                            Name = "Juan's Pizza Palace",
                            PhoneNumber = "8468618684",
                            Type = "restaurant",
                            UserId = 2,
                            WebSite = "castor oil"
                        },
                        new
                        {
                            BusinessId = 2,
                            Description = "Mix 2 drops eucalyptus oil, 1 drop peppermint oil, and 1 drop tea tree oil into 1 oz neutral oil or balm.  Rub on sore muscles before sleep.",
                            Name = "Joly Jands Joliday Joopla",
                            PhoneNumber = "7878799456",
                            Type = "restaurant",
                            UserId = 2,
                            WebSite = "https://www.google.com/"
                        },
                        new
                        {
                            BusinessId = 3,
                            Description = "Mega doses of Omega 3s for LIFE!!!!",
                            Name = "Don't Eat Anywhere Else",
                            PhoneNumber = "3743453457",
                            Type = "restaurant",
                            UserId = 1,
                            WebSite = "https://www.google.com/"
                        },
                        new
                        {
                            BusinessId = 4,
                            Description = "Soak the affected area in apple cider vinegar twice a day until cured",
                            Name = "Mycelium and Moss",
                            PhoneNumber = "9757567677",
                            Type = "shop",
                            UserId = 2,
                            WebSite = "https://www.google.com/"
                        },
                        new
                        {
                            BusinessId = 5,
                            Description = "One shot of vodka, followed by one shot of fresh ginger juice, daily until symptoms resolve.",
                            Name = "The Soap Shop",
                            PhoneNumber = "3684568654",
                            Type = "shop",
                            UserId = 1,
                            WebSite = "https://www.google.com/"
                        },
                        new
                        {
                            BusinessId = 6,
                            Description = "apply earl grey tea to the affected area 5 times a day until burn goes away",
                            Name = "Get Wellness!",
                            PhoneNumber = "8141465465",
                            Type = "shop",
                            UserId = 2,
                            WebSite = "https://www.google.com/"
                        },
                        new
                        {
                            BusinessId = 7,
                            Description = "Heat 4 oz water to body temperature.  Add 1 oz fresh lemon juice. Drink slowly.",
                            Name = "I Need",
                            PhoneNumber = "6565656565",
                            Type = "shop",
                            UserId = 1,
                            WebSite = "lemon"
                        },
                        new
                        {
                            BusinessId = 8,
                            Description = "Mix 2 drops eucalyptus oil, 1 drop peppermint oil, and 1 drop tea tree oil into 1 oz neutral oil or balm.  Rub on throat, chest and upper back before sleep.",
                            Name = "Good Times Clock Shop",
                            PhoneNumber = "9876543212",
                            Type = "shop",
                            UserId = 2,
                            WebSite = "https://www.google.com/"
                        },
                        new
                        {
                            BusinessId = 9,
                            Description = "If something is in your eye, pull your upper eyelid over your lower one, in an attempt to scrape out the obstruction",
                            Name = "Zebra Print Bread",
                            PhoneNumber = "0212121212",
                            Type = "restaurant",
                            UserId = 1,
                            WebSite = "https://www.google.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
